### ISSUE TITLE
Version 1.2.0 does not install Autofac.Extras.NSubstitute;

### ISSUE THREAD

**Issue by mes1234** [zskovacs/Autofac.Extras.NSubstitute#5]
Hello,

I've encountered an error when I installed 
Install-Package Autofac.Extras.NSubstitute -Version 1.2.0
I got error while trying to : using Autofac.Extras.NSubstitute
Downgrading to v.1.1.0 resolves this issue.
Tests project is based on netcoreapp3.1

Thanks!

**Comment by luisabreu** [comment]
This is still happening with net 7.0 test projects.

**Comment by Kromzem** [comment]
Fixed this with version 1.3.0 and PR #6
